### ISSUE TITLE
Fonts.com (Monotype) fonts never load

### ISSUE THREAD

**Issue by laurence-myers** [typekit/webfontloader#318]
In an AngularJS app, calling WebFont.load() with a config. No events get triggered aside from "loading". Other providers seem okay (e.g. custom fonts will load and trigger all events), although getting custom fonts and Monotype fonts will never trigger the "active" event.

The network traffic seems fine; it loads "mti_otf.js", and four "otf_*OTFFeatDisabled.js" files (representing the four fonts in the Fonts.com account/project). It also loads an empty CSS file "https://fast.fonts.net/t/1.css?apiType=js&projectid=xxx-yyy-zzz" (where "xxx-yyy-zzz" is my Monotype project ID).

I've dug into the code, looks like the Monotype module is checking for a property "__mti_fntLstxxx-yyy-zzz" on the Window, seems like this never gets set. The "mti_otf.js" code seems to set this to a function, but the file is minified, so it's a bit tricky to debug.

Any ideas what's wrong?

Minimal reproducible HTML & JS (must be served from a domain authorized for your Monotype project):
https://gist.github.com/laurence-myers/d0322e86f33406dec64d

**Comment by laurence-myers** [comment]
I have a suspicion our Fonts.com subscription was downgraded, maybe this is causing fonts to fail to load. However, that means webfontloader is not detecting the font load failures.

Looks like the Monotype JS exposes a "MonoTypeWebFonts" object; using breakpoints, I can see that the "inactive" method is called, but no others.

**Comment by bramstein** [comment]
@laurence-myers The Monotype module is maintained by the Monotype team, there is unfortunately not much we (Typekit) can do. I suggest reaching out to their support. Sorry I can't be of more help.

**Comment by laurence-myers** [comment]
@ramghaju, looks you last updated the Monotype module. Are you able to advise on this issue?

**Comment by ramghaju** [comment]
@laurence-myers, I have checked the HTML page you have shared here. 
https://gist.github.com/laurence-myers/d0322e86f33406dec64d

In this page, you have used "p" tag for content "hello". As you're not sharing your projectId, I am not able to check whether you have added font for this tag or not from fonts.com project. Based on the html, it seems no webfonts are used on this test page. Will you please check adding any font from fonts.com on this page? it should work. 

You're correct, we're waiting for "__mti_fntLst_PROJECTID". It contains list of fonts for which needs to fire font event. We're passing only the used fonts to this list. You must have to use at least one font from your project to make other font event fires. 

Please let us know if you're still facing the issue.

**Comment by laurence-myers** [comment]
Thanks for looking into it @ramghaju!

For my example code, I was monitoring the console to see if callbacks were triggered, sorry I did not state that as my "expected behaviour".

For my use case, I'm using the fonts in a canvas renderer in an image template system. So, no actual font usage in the HTML or CSS.

The fonts we use are dynamically configured, set per "client", each client making use of fonts from different sources (including Monotype). In order to enumerate the available fonts per client, so I can display them as options in a dropdown, I was relying on the webfontloader callbacks like "fontactive".

Is there a way to get the list of available fonts for a Monotype package? That way, I can work around the issue by creating dummy elements that use each font.

Regardless, the existing Monotype module appears to be faulty. If no fonts are loaded (because no fonts are used), it should propogate the "inactive" event to webfontloader; otherwise, the Monotype loader will never finish loading, which in my case will block further processing - I need to know when all fonts have finished loading before my users can continue their work.

@bramstein Is there some guarantee/contract on how loader modules should behave? I.e. Monotype only loads fonts that are already used on the page, whereas other modules do not appear to do so (e.g. Google, custom, and Typekit)

**Comment by ramghaju** [comment]
@laurence-myers,
We offer both latin and CJK(Chinese Japanese Korean) webfonts from fonts.com. You know the size of CJK fonts, in general, will be larger. If we fire font events for all fonts although not consumed by page which are included in fonts.com project as per your expectation, user will have to wait for long time. To prevent this issue, we're passing just  the list of fonts which are used on the page.

To get list of fonts from Monotype package, you can use our public APIs. You can contact our support for more details.

**Comment by laurence-myers** [comment]
@ramghaju I don't understand. If the user does not load a font, why would it take a long time to fire an "inactive" event to webfontloader?

You seem to be skirting the issue of the Monotype loader behaving badly, with regards to not informing webfontloader of events (i.e. font loaded, font not loaded, all font loading finished with at least one success, no fonts loaded). What's the advantage of using Monotype through webfontloader, vs directly through Monotype's own APIs, if the loader is not integrating with webfontloader like every other loader?

**Comment by ramghaju** [comment]
@laurence-myers,

We are having discussion within our team to provide separate configuration **option**, that will allow to load all fonts in project. Hope this helps you to get the behavior you expect.

To fire events like ```fontloading/fontactive/active```, **webfontloader** needs to download the fonts (even though font is not used on the page). With intention of saving bandwidth of our end-users, we only provide the list of fonts which are currently being used on page. 

We have already mentioned that we also serve Chinese-Japanese-Korean fonts (CJK), which can be very large (e.g. 20-50MB). We are one of the prominent providers for CJK fonts, and have huge customer base who uses those fonts. Hence we cannot allow browser to blindly download every font in project, it would have huge implication in page performance and user experience.

**Comment by laurence-myers** [comment]
@ramghaju Having that option would be great! :+1:

I misunderstood how the events were triggered. It sounds like they come from the browser's font loading mechanism, and not anything to do with the individual loader modules. In that case, it now makes sense why events are not triggered as I expected (because the fonts are only being loaded as they're needed).

For now, I will probably implement a workaround, to dynamically create HTML elements using the required fonts, before invoking webfontloader.

**Comment by janaagaard75** [comment]
@laurence-myers I'm having the exact same issue.

Did you implement this workaround with a dynamically created HTML element or did you find another solution? Did it work? :)

**Comment by janaagaard75** [comment]
Also: It seems that for really small projects, with just a few fonts, the loading event is being triggered. I guess that this is because Web Font Loader determines that the loading impact is so small, that it might as well just load the fonts. Can you confirm this @ramghaju?

**Comment by laurence-myers** [comment]
@janaagaard75 Yes, I found another solution - use a different font provider! ;)

This got put in the "too hard" basket, so I haven't investigated any further, I'm afraid.

**Comment by ramghaju** [comment]
@janaagaard75, it works fine with all size of project regardless of number of fonts added on the project. To avoid users' page performance degradation due to downloading unused fonts, we're passing only the "used" project fonts to the webfont loader. We're implementing the option we shared with @laurence-myers.

**Comment by janaagaard75** [comment]
What I was seeing (or thought that I was seeing) was that under some circumstances, the fonts would actually be pre-loaded even thought none of them were used by the web page. I have, however, not been able to reproduce this consistently, so I guess this was just a fluke.

Do you have an estimate on when it will be possible to force downloading of the fonts?

**Comment by ramghaju** [comment]
We have started implementing it. We're planning to release this feature by this weekend.

**Comment by janaagaard75** [comment]
Really cool, @ramghaju. Looking forward to using it. 👍

**Comment by ramghaju** [comment]
@janaagaard75, we have released our latest code. Please add new optional option "loadAllFonts:true"   in configuration. It will force all project fonts to trigger font events. This option will be "false" by default.

**Comment by janaagaard75** [comment]
Looking really good. It seems to do exactly as expected, and I don't have any issues. I'll get back if I find anything, but if I don't, it means that is just works. Nice job.

**Comment by janaagaard75** [comment]
@ramghaju 

I think I celebrated too soon. It was the issue with really font projects downloading the fonts anyways. I have now been able to create the issue in a very isolated environment. It's actually two issues:

Here the two fonts are downloaded even though loadAllFonts is set to false and none of the fonts are in use.
http://run.plnkr.co/plunks/mrxcQyAZ6cz2XTwc1OJH/

Here loadAllFonts is set to true, but none of the fonts are downloaded.
http://run.plnkr.co/plunks/Uu4mqicLUyF6lFHMoVQp/

**Comment by ramghaju** [comment]
@janaagaard75, we're looking into these issues. We'll contact you as soon as possible.

**Comment by janaagaard75** [comment]
Any updates on the issues, @ramghaju?

Should I create a separate issue about the fonts are being downloaded, even though they aren't being used on the page? The problem doesn't really match the description of this issue.

**Comment by ramghaju** [comment]
@janaagaard75, the issue is already fixed. In your test page, both pages are not downloading any fonts. We have already verified it. We're waiting for code merge of our pull request to make new option "loadAllfonts" working.

**Comment by janaagaard75** [comment]
Thanks. Looking forward to the pull request being merged. :)

**Comment by bramstein** [comment]
Thanks to @ramghaju, this change is now in Web Font Loader v1.6.25.

**Comment by laurence-myers** [comment]
Thanks very much @ramghaju (and your team) for making changes to support my use case! Looks like a good solution. :)
Thanks @bramstein for mediating and merging!

**Comment by janaagaard75** [comment]
I upgraded my little test page to v1.6.25, but the fonts are still not being loaded. Is there anything else I need to do?

http://run.plnkr.co/plunks/Uu4mqicLUyF6lFHMoVQp/

**Comment by ramghaju** [comment]
@janaagaard75, we're releasing our code. I will update you once code release will be done.

**Comment by ramghaju** [comment]
@janaagaard75 , We have released the code. 
Thanks you all for your support. @bramstein @laurence-myers
